"""Add new conversation, conversation_member and message table

Revision ID: 0a6c4cc198aa
Revises: ed8332b5fe7d
Create Date: 2024-12-19 11:17:25.504951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a6c4cc198aa'
down_revision = 'ed8332b5fe7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('conversation_name', sa.String(length=1000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('conversation_member',
    sa.Column('infor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('infor_id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation_member')
    op.drop_table('conversation')
    # ### end Alembic commands ###
