"""Add new column

Revision ID: 1ed00f440e9a
Revises: f5557a41c862
Create Date: 2025-01-16 17:30:28.481559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ed00f440e9a'
down_revision = 'f5557a41c862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_pairing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'EXECUTING', 'COMPLETE', name='statusmatch'), nullable=False),
    sa.Column('actual_departure_time', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_pairing_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_pairing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('schedule_pairing_managemen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_pairing_managemen_id'], ['schedule_pairing_management.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_share',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('schedule_management_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_management_id'], ['schedule_management.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roadmap_pairing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('roadmap_pairing_id', sa.Integer(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_pairing_id'], ['roadmap_pairing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_share',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('estimated_departure_time', sa.DateTime(), nullable=False),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=False),
    sa.Column('schedule_share_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.ForeignKeyConstraint(['schedule_share_id'], ['schedule_share.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedulepairing_roadmappairing',
    sa.Column('schedule_pairing_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_pairing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_pairing_id'], ['roadmap_pairing.id'], ),
    sa.ForeignKeyConstraint(['schedule_pairing_id'], ['schedule_pairing.id'], ),
    sa.PrimaryKeyConstraint('schedule_pairing_id', 'roadmap_pairing_id')
    )
    op.create_table('roadmap_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('FREE', 'MATCHING', 'PENDING', 'WAITING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='status'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('roadmap_share_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=200), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_share_id'], ['roadmap_share.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request')
    op.drop_table('routeshare')
    op.drop_table('matchroute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchroute',
    sa.Column('match_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('matched_time', mysql.DATETIME(), nullable=False),
    sa.Column('main_user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('secondary_user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('route_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('WAITING', 'EXECUTING', 'COMPLETE'), nullable=False),
    sa.Column('start_time_actual', mysql.DATETIME(), nullable=True),
    sa.Column('end_time_actual', mysql.DATETIME(), nullable=True),
    sa.Column('route_share_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['user.user_id'], name='matchroute_ibfk_1'),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], name='matchroute_ibfk_3'),
    sa.ForeignKeyConstraint(['route_share_id'], ['routeshare.share_id'], name='matchroute_ibfk_4'),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.user_id'], name='matchroute_ibfk_2'),
    sa.PrimaryKeyConstraint('match_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('routeshare',
    sa.Column('share_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('is_match', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('share_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('share_description', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('share_date', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('route_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], name='routeshare_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='routeshare_ibfk_1'),
    sa.PrimaryKeyConstraint('share_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('request',
    sa.Column('request_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status', mysql.ENUM('FREE', 'MATCHING', 'PENDING', 'WAITING', 'ACCEPTED', 'DECLINED', 'CANCELLED'), nullable=False),
    sa.Column('created_time', mysql.DATETIME(), nullable=False),
    sa.Column('main_user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('secondary_user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('route_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['user.user_id'], name='request_ibfk_1'),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], name='request_ibfk_3'),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.user_id'], name='request_ibfk_2'),
    sa.PrimaryKeyConstraint('request_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('roadmap_request')
    op.drop_table('schedulepairing_roadmappairing')
    op.drop_table('roadmap_share')
    op.drop_table('user_roadmap_pairing')
    op.drop_table('schedule_share')
    op.drop_table('schedule_pairing')
    op.drop_table('schedule_pairing_management')
    op.drop_table('schedule_management')
    op.drop_table('roadmap_pairing')
    # ### end Alembic commands ###
