"""Add RequestRoute model

Revision ID: 42ef02a17df5
Revises: f172a5518fd4
Create Date: 2024-12-07 09:58:53.020929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ef02a17df5'
down_revision = 'f172a5518fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('noti_type', sa.Enum('REQUEST', 'OTHER', name='notificationtype'), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.Column('secondary_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('FREE', 'MATCHING', 'PENDING', 'WAITING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='status'), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.Column('secondary_user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('notification')
    # ### end Alembic commands ###
