"""Add share_name column to UserRouteShare table

Revision ID: 4a3a46c93313
Revises: 
Create Date: 2024-11-30 15:49:08.391266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3a46c93313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routeshare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_name', sa.String(length=255), nullable=False))
        batch_op.alter_column('share_description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routeshare', schema=None) as batch_op:
        batch_op.alter_column('share_description',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.drop_column('share_name')

    # ### end Alembic commands ###
