"""Add conversation, conversation_group, message, message_group, group_member table to DB

Revision ID: 612b692305a7
Revises: 0a6c4cc198aa
Create Date: 2024-12-20 23:04:54.829801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '612b692305a7'
down_revision = '0a6c4cc198aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('main_user_id', sa.Integer(), nullable=False),
    sa.Column('secondary_user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['main_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('conversation_group',
    sa.Column('conversation_name', sa.String(length=1000), nullable=False),
    sa.Column('photo', sa.String(length=1000), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('group_member',
    sa.Column('infor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['conversation_group.conversation_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('infor_id')
    )
    op.create_table('message',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('message_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['conversation_group.conversation_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_group')
    op.drop_table('message')
    op.drop_table('group_member')
    op.drop_table('conversation_group')
    op.drop_table('conversation')
    # ### end Alembic commands ###
