"""Add some column

Revision ID: 89b0c03dccbc
Revises: 61e922cad67d
Create Date: 2025-03-06 17:52:30.848316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89b0c03dccbc'
down_revision = '61e922cad67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_pairing', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('WAITING', 'CANCELLED', 'COMPLETED', 'NOT_STARTED', 'IN_PROGRESS', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('WAITING', 'COMPLETED', 'NOT_STARTED', 'IN_PROGRESS', 'CANCELLED', name='statusmatch'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_pairing', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('WAITING', 'COMPLETED', 'NOT_STARTED', 'IN_PROGRESS', 'CANCELLED', name='statusmatch'),
               type_=mysql.ENUM('WAITING', 'CANCELLED', 'COMPLETED', 'NOT_STARTED', 'IN_PROGRESS', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
