"""Something changed

Revision ID: 8e5ecfca2a1c
Revises: b62f7c243d24
Create Date: 2025-02-02 09:22:28.277944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5ecfca2a1c'
down_revision = 'b62f7c243d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_pairing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_share_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'roadmap_share', ['roadmap_share_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_pairing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roadmap_share_id')

    # ### end Alembic commands ###
