"""fix column name

Revision ID: b895367a8918
Revises: 8e5ecfca2a1c
Create Date: 2025-02-02 10:55:50.004844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b895367a8918'
down_revision = '8e5ecfca2a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roadmap_pairing')
    with op.batch_alter_table('roadmap_pairing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_request_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('roadmap_pairing_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('roadmap_pairing_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roadmap_request', ['roadmap_request_id'], ['id'])
        batch_op.drop_column('route_id')
        batch_op.drop_column('roadmap_share_id')

    with op.batch_alter_table('schedule_pairing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_pairing_management_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('schedule_pairing_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'schedule_pairing_management', ['schedule_pairing_management_id'], ['id'])
        batch_op.drop_column('schedule_pairing_managemen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_pairing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_pairing_managemen_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_pairing_ibfk_1', 'schedule_pairing_management', ['schedule_pairing_managemen_id'], ['id'])
        batch_op.drop_column('schedule_pairing_management_id')

    with op.batch_alter_table('roadmap_pairing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_share_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('route_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roadmap_pairing_ibfk_2', 'roadmap_share', ['roadmap_share_id'], ['id'])
        batch_op.create_foreign_key('roadmap_pairing_ibfk_1', 'route', ['route_id'], ['route_id'])
        batch_op.drop_column('roadmap_request_id')

    op.create_table('user_roadmap_pairing',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('roadmap_pairing_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_host', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('joined_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_pairing_id'], ['roadmap_pairing.id'], name='user_roadmap_pairing_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_roadmap_pairing_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
