"""Add some new column to DB and modify column

Revision ID: f5557a41c862
Revises: 34ceed9e44ea
Create Date: 2025-01-12 18:56:09.742405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5557a41c862'
down_revision = '34ceed9e44ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchroute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('WAITING', 'EXECUTING', 'COMPLETE', name='statusmatch'), nullable=False))
        batch_op.add_column(sa.Column('start_time_actual', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time_actual', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('route_share_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'routeshare', ['route_share_id'], ['share_id'])
        batch_op.drop_column('is_match')

    with op.batch_alter_table('routeshare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routeshare', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('matchroute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_match', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('route_share_id')
        batch_op.drop_column('end_time_actual')
        batch_op.drop_column('start_time_actual')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
